apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-ci-pipelines-exporter-services
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: http-services
  selector:
    matchLabels:
      app: gitlab-ci-pipelines-exporter-services
