{
 "title": "Kubernetes StatefulSet Statistics",
 "description": "This dashboard leverages the Prometheus kube-state-metrics exporter. I implemented custom Grafana Dshboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas{namespace=~\"$NAMESPACE\"}, namespace)"
    }
   },
   {
    "name": "STATEFULSET",
    "label": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas_available{statefulset=~\"$STATEFULSET\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://learnk8s.io/a/kubernetes-wallpapers/magician-1536x864.png\" width=240px/></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "AVAILABLE STATEFULSETS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_status_replicas_available)"
    }
   ]
  },
  {
   "title": "CREATED (in the last hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_statefulset_created[1h]))"
    }
   ]
  },
  {
   "title": "STATEFULETS",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_available{statefulset=~\"$STATEFULSET\"}) by (statefulset)",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "STATEFULSETS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_status_replicas)"
    }
   ]
  },
  {
   "title": "Average Statefulset Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_available)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STATEFULSETS READY",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{statefulset=~\"$STATEFULSET\"} > 0) by (statefulset)"
    }
   ]
  },
  {
   "title": "STATEFULSETS AVAILABLE",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_available{statefulset=~\"$STATEFULSET\"} > 0) by (statefulset)"
    }
   ]
  },
  {
   "title": "STATEFULSETS UNAVAILABLE",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(sum(kube_statefulset_status_replicas{statefulset=~\"$STATEFULSET\"}) - sum(kube_statefulset_status_replicas_available{statefulset=~\"$STATEFULSET\"}) > 0)"
    }
   ]
  }
 ]
}