{
 "title": "Kubernetes Deployments Statistics",
 "description": "This dashboard leverages the Prometheus kube-state-metrics exporter. I implemented custom Grafana Dshboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "NAMESPACE",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=~\"$NAMESPACE\"}, namespace)"
    }
   },
   {
    "name": "DEPLOYMENT",
    "label": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{deployment=~\"$DEPLOYMENT\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://learnk8s.io/a/kubernetes-wallpapers/magician-1536x864.png\" width=240px/></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "AVAILABLE DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas_available > 0)"
    }
   ]
  },
  {
   "title": "CREATED (in the last hour)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_deployment_created[1h]))"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$DEPLOYMENT\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas)"
    }
   ]
  },
  {
   "title": "Average Deployments Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_deployment_status_replicas_available)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS READY",
   "type": "table",
   "gridPos": { "h": 30, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_ready{deployment=~\"$DEPLOYMENT\"} > 0) by (deployment)"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS AVAILABLE",
   "type": "table",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$DEPLOYMENT\"} > 0) by (deployment)"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS UNAVAILABLE",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$DEPLOYMENT\"} > 0) by (deployment)"
    }
   ]
  }
 ]
}